---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pr-3
  namespace: argocd
spec:
  destination:
    namespace: pr-3
    server: https://kubernetes.default.svc
  project: previews
  source:
    path: guestbook
    repoURL: https://github.com/bulatzamilov/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
